language: python
python: 3.7
cache: pip
branches:
  only:
  - master
install:
  - pip install pre-commit sceptre
  - npm install -g aws-organization-formation
stages:
  - name: validate
  - name: deploy
    if: branch = master AND type = push
jobs:
  fast_finish: true
  include:
    - stage: validate
      script:
        - pre-commit run --all-files
    - stage: deploy
      name: "organizations"
      script:
        - export ACCOUNT="organizations"
        - ./setup_aws_cli.sh $ACCOUNT || travis_terminate 1
        - sceptre launch $ACCOUNT --yes
        - org-formation perform-tasks org-formation/organization-tasks.yaml --verbose --print-stack
    - stage: deploy
      name: "burner"
      script:
        - export ACCOUNT="burner"
        - ./setup_aws_cli.sh $ACCOUNT || travis_terminate 1
        - sceptre launch $ACCOUNT --yes
    - stage: deploy
      name: "sandbox"
      script:
        - export ACCOUNT="sandbox"
        - ./setup_aws_cli.sh $ACCOUNT || travis_terminate 1
        - sceptre launch $ACCOUNT --yes
